### ISSUE TITLE
not executable a non-root

### ISSUE THREAD

**Issue by audiophiel** [tolga9009/sidewinderd#9] opened 2016-02-19 15:44 UTC
After the boot, there is a a process "sidewinderd" (by the users root and me) and the .pid file is created (in my unencrypted home folder). The "M1" key is illuminated, but nothing happens (neither by pressing the M nor the G-keys).

EDIT: Im using the Logitech G710+ on Linux with the 4.5 kernel.
EDIT2: after killing the process and starting it (as non root) i get this:

I/O error while writing file.
Sidewinderd v0.3.1 has been started.
Found device: 046d:c24d
Can't open hidraw interface

**Comment by tolga9009** [comment] 2016-02-19 18:07
Hi there,

well, I think I need to clean up some confusion. First of all, sidewinderd generally needs to be run as a root user in order to access your USB keyboard - else, it won't work out of the box. Of course, you could also define custom udev rules, but it just adds complexity - it's easier to run sidewinderd as root.

`I/O error while writing file.` indicates, that sidewinderd is trying to write a default configuration file to `/etc/sidewinderd.conf` and it doesn't have access to it. This will also be solved by running sidewinderd as root.

However, you can configure a user in the `/etc/sidewinderd.conf` (default is `root`), which will be used for saving profiles / macros. This is the configuration you're looking for.

E.g. you set user to `tolga` in `/etc/sidewinderd.conf`, then your macro files will get saved under `/home/tolga/.local/share/sidewinderd/<profile>/<macro>.xml`.

There is no default action attached to G1 - G6 keys out of the box. You will need to record macros. There is a brief instruction in the project's ReadMe file.

M1 - M3 keys are non-programmable. Pressing them will let you choose the active profile. This gives you the opportunity to have 18 programmable keys. The XML files are human-readable and easy to edit by hand.

Hope this clears everything up a bit.

Cheers,
Tolga

**Comment by audiophiel** [comment] 2016-02-19 18:16
Hey, thaks for the quick answer and the explanation!
The content of /etc/sidewinderd.conf is:

user = "audiophiel;
profile = 1;
capture_delays = false;
pid-file = "/home/audiophiel/.sidewinderd.pid";

But after booting the system (i executed systemctl enable sidewinderd.service before) i have to kill the process and restart it again to get it to work.

Cheers,
Severin

**Comment by tolga9009** [comment] 2016-02-19 18:17
I see. By any chance, is your home folder encrypted?

**Comment by audiophiel** [comment] 2016-02-19 18:17
no, thats whats puzzeling me...

**Comment by tolga9009** [comment] 2016-02-19 18:19
Please try using the default location for the pid-file: `/var/run/sidewinderd.pid`. I haven't tested custom locations for the pid-file to be honest.

**Comment by audiophiel** [comment] 2016-02-19 18:24
The pid-file was created in my home folder. But i changed it to the locationyou suggested - no change (i still have to restart the process by hand).

**Comment by tolga9009** [comment] 2016-02-19 18:26
Which Linux distribution are you using? And are you using systemd?

**Comment by audiophiel** [comment] 2016-02-19 18:31
I use OS: Manjaro 15.12 Capella (an arch linux deviant) with the Kernel: x86_64 Linux 4.5.0-1-MANJARO, and yes i use systemd

**Comment by tolga9009** [comment] 2016-02-19 18:37
Last question: are you using the AUR package (https://aur.archlinux.org/packages/sidewinderd)?

**Comment by audiophiel** [comment] 2016-02-19 18:38
yes

**Comment by tolga9009** [comment] 2016-02-19 18:42
Okay, I think I can opt out an install issue then. I will download Manjaro 15.12 and test it with my system. Maybe there is something specific. I've also noticed, that you are missing a double quite in `user = "audiophiel;`. It should be `user = "audiophiel";`.

I'm gonna report back after testing.

**Comment by audiophiel** [comment] 2016-02-19 18:44
thanks for your effort! the forgotten " was a coppy/paste mistake, it's there in the file:)

**Comment by tolga9009** [comment] 2016-02-21 13:46
Okay, I was finally able to set up Manjaro Linux 15.12 KDE and didn't run into any problems. sidewinderd was successfully able to initialize, find the device and handle it.

Could you please give me the output of `systemctl status sidewinderd` right after system boot, when sidewinderd fails? I assume, that either the filesystem is not ready or it fails to detect your USB device, due to various reasons (like a late USB start up).

In case it's waiting for your filesystem, please try the following:
1. `sudo cp /usr/lib/systemd/system/sidewinderd.service /etc/systemd/system/`
2. Edit this newly copied sidewinderd.service file in `/etc/...` and add `RequiresMountsFor=/home/` under `[Unit]`, so your resulting file will be like this: https://gist.github.com/tolga9009/56e93225f18d463ba838
3. Disable old service file (in `/usr/...`) `systemctl disable sidewinderd`
4. Enable new service file (in `/etc/...`) `systemctl enable sidewinderd` (systemd will automatically use `/etc` service files over `/usr`, if they're available.
5. Reboot.

Hope it helps!

Apart from this specific issue, I need to improve error handling in sidewinderd. It's a bit poor at the moment, I will improve it.

Cheers,
Tolga

**Comment by audiophiel** [comment] 2016-02-21 14:07
Hey, its amazing, that you care so much abbout this!

For some reason the sidewinderd-process starts normal:

$ systemctl status sidewinderd
● sidewinderd.service - Daemon for handling Microsoft SideWinder X4 / X6 and Logitech G710+
   Loaded: loaded (/usr/lib/systemd/system/sidewinderd.service; enabled; vendor preset: disabled)
   Active: active (running) since So 2016-02-21 14:58:08 CET; 4min 19s ago
 Main PID: 424 (sidewinderd)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/sidewinderd.service
           └─424 /usr/bin/sidewinderd

Feb 21 14:58:08 box systemd[1]: Started Daemon for handling Microsoft SideWinder X4 / X6 and Logitech G710+.
Feb 21 14:58:08 box sidewinderd[424]: Sidewinderd v0.3.1 has been started.
Feb 21 14:58:08 box sidewinderd[424]: Found device: 046d:c24d

but it can't write the recorded Macros to a file:

$ systemctl status sidewinderd
● sidewinderd.service - Daemon for handling Microsoft SideWinder X4 / X6 and Logitech G710+
   Loaded: loaded (/usr/lib/systemd/system/sidewinderd.service; enabled; vendor preset: disabled)
   Active: active (running) since So 2016-02-21 14:58:08 CET; 7min ago
 Main PID: 424 (sidewinderd)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/sidewinderd.service
           └─424 /usr/bin/sidewinderd

Feb 21 14:58:08 box systemd[1]: Started Daemon for handling Microsoft SideWinder X4 / X6 and Logitech G710+.
Feb 21 14:58:08 box sidewinderd[424]: Sidewinderd v0.3.1 has been started.
Feb 21 14:58:08 box sidewinderd[424]: Found device: 046d:c24d
Feb 21 14:58:34 box sidewinderd[424]: Start Macro Recording on
Feb 21 14:58:34 box sidewinderd[424]: Can't open input event file
Feb 21 14:58:37 box sidewinderd[424]: Exit Macro Recording
Feb 21 15:02:16 box sidewinderd[424]: Start Macro Recording on
Feb 21 15:02:16 box sidewinderd[424]: Can't open input event file
Feb 21 15:02:22 box sidewinderd[424]: Exit Macro Recording

I'm abbout todo a clean install of my system anyway, so maybe that will solve the problem. I'll keep you posted

Cheers,
audiophiel

**Comment by tolga9009** [comment] 2016-02-21 14:43
Hmm, weird. It can't access the `/dev/input/event*` file in order to listen to your keyboard. Disable siderwinderd on boot and run it in a commandline: `sudo sidewinderd`. Does macro recording etc. work?

**Comment by audiophiel** [comment] 2016-02-21 15:24
after stopping the process and executing `sudo sidewinderd` it works like a charm. yes, it was the only process. And i did a clean fresh install, it didn't change anything.

audiophiel

**Comment by tolga9009** [comment] 2016-02-21 15:32
Okay, I think I know what's going on. Initializing the input subsystem (`/dev/input/event*`) seems to take longer than usual on your system and sidewinderd is unable to find it on boot. I need the `findDevice()` function to fail on such an event - a very good point, thanks for reporting the bug!

I will look, if I can find a quickfix for you, else you will need to wait for the next version to get this fixed. But no need to say, this has top priority for me, I will work on this next.

**Comment by audiophiel** [comment] 2016-02-21 15:33
thanks! you are the best!

**Comment by tolga9009** [comment] 2016-02-21 16:18
I have a quick & dirty solution for you, which will let sidewinderd.service sleep for a while. Still, to find out, what's the problem, I need to follow the following instructions first:

1. `sudo systemctl disable sidewinderd`
2. `sudo rm /etc/systemd/system/sidewinderd.service`
3. `sudo systemctl enable sidewinderd`
4. Reboot
5. `systemd-analyze plot > systemd-analyze.svg`. This will create an svg file in your working directory (check your working directory with command `pwd`). Make sure you have write access to your working directory, else change it via `cd`.
6. Upload that svg file here via drag & drop or feel free to send it over to my public E-Mail adress (view on my GitHub profile page). This way, I can analyze your boot sequence, compare it with mine and find the culprit.

I'm now testing the service file and upload it here.

**Comment by audiophiel** [comment] 2016-02-21 16:21
im compiling something right now, i will do the procedure in ~1h and come back to you than  thx.

**Comment by tolga9009** [comment] 2016-02-21 16:26
I have uploaded the service file here: https://gist.github.com/tolga9009/7ab5c0e3091994a3f660. You will need to copy this over to `/etc/systemd/system` and re-enable the systemd sidewinderd serivce.

I hope it helps!

Cheers,
Tolga

**Comment by audiophiel** [comment] 2016-02-21 16:30
should i skip the part with generating the svg, or would you prefere the svg file before i use your updated sidewinderd.service?

**Comment by tolga9009** [comment] 2016-02-21 16:32
I would prefer to have the SVG file before. I need to know, why sidewinderd is failing on your system. Only then, I will be able to fix this problem by its root, without the nasty sleep fix.

**Comment by audiophiel** [comment] 2016-02-21 21:11
So i applied your hotfix, and it did the job.
Thanks!

**Comment by tolga9009** [comment] 2016-02-27 10:21
I was able to reproduce this issue, by playing around with systemd service files (using `Before` and `After`). However, I was not able to find out, which service was responsible for the initialization of `/dev/input/event*`.

Waiting for `multi-user.target` definitely fixed this issue in my scenario - and it makes sense. There is no use for your keyboard until `multi-user.target` anyway, so waiting for it is reasonable. This doesn't increase boot time or have any other negative effects - it's just fixing this issue.

This got fixed in 2c4c2f7453b7de077e28481e0e638b3b5d75fe17. I'm closing this issue now. Please re-open it, if you still have problems. I'm now trying to fix #6, a new version of sidewinderd will be pushed out after that.

Cheers,
Tolga

**Closed by tolga9009** 2016-02-27 10:21 UTC
